added CSS
JFCotter/regpage-dev-project pull request #2
Opened 2023-11-21 11:21 UTC by JFCotter

2023-11-23 09:02 UTC, mkyorov-ageas requested changes

2023-11-23 09:02 UTC, ghost commented on src/styles.css
> +
Add reset styles on top here.

2023-11-23 09:02 UTC, ghost commented on src/styles.css
> +p {
you should never do that. This applies certain styles to all "p" elements in your document. For styling always use classes

2023-11-23 09:02 UTC, ghost commented on src/styles.css
> +  margin-bottom: 22px;
to save 1 line of code you could do "margin: 22px 0", this will apply margin top/bottom 22px and left/right 0px;

2023-11-23 09:02 UTC, ghost commented on src/styles.css
> +header {
never use html tags for styling

2023-11-23 09:02 UTC, ghost commented on src/styles.css
> +#logoWhiteFont {
For styling we always use styles and id-s to write JS code

2023-11-23 09:02 UTC, ghost commented on src/styles.css
> +main {
Again, don't use html tags for styling

2023-11-23 09:02 UTC, ghost commented on src/styles.css
> +  margin-bottom: 40px;
you could do 1 line for all margin properties like -> margin: 40px auto;

2023-11-23 09:02 UTC, ghost commented on src/styles.css
> +h1 {
No tags for styling

2023-11-23 09:02 UTC, ghost commented on src/styles.css
> +  color: white;
For colors you should choose one way of defining them, either HEX or RGB

2023-11-23 09:02 UTC, ghost commented on src/styles.css
> +  max-width: 80%;
You may want to reconsider that, think responsive design on 70 inch monitor, the form would be huge, but the rest of the content would be very small

2023-11-23 09:02 UTC, ghost commented on src/styles.css
> +h2 {
You gotta be a little more creative with class names :D

2023-11-23 09:02 UTC, ghost commented on src/styles.css
> +  border-color: rgb(160, 160, 160);
use the shorthand property for border

2023-11-23 09:02 UTC, ghost commented on src/styles.css
> +  border-width: 1px;
Shorthand border property

2023-11-23 09:02 UTC, ghost commented on src/styles.css
> +  background-repeat: no-repeat;
use background property to set all values together

2023-11-23 09:02 UTC, ghost commented on src/styles.css
> +#year {
No id-s

2023-11-23 09:02 UTC, ghost commented on src/styles.css
> +span {
No html tags

2023-11-28 10:08 UTC, JFCotter commented on src/styles.css
> +
done

2023-11-28 10:08 UTC, JFCotter commented on src/styles.css
> +  max-width: 80%;
changed to use padding, removed margin: auto

2023-11-28 10:08 UTC, JFCotter commented on src/styles.css
> +p {
undone

2023-11-28 10:08 UTC, JFCotter commented on src/styles.css
> +  margin-bottom: 22px;
done

2023-11-28 10:08 UTC, JFCotter commented on src/styles.css
> +header {
undone

2023-11-28 10:08 UTC, JFCotter commented on src/styles.css
> +#logoWhiteFont {
converted all ids to classes, apart from in input elements

2023-11-28 10:08 UTC, JFCotter commented on src/styles.css
> +  border-color: rgb(160, 160, 160);
done

2023-11-28 10:08 UTC, JFCotter commented on src/styles.css
> +  border-width: 1px;
done

2023-11-28 10:08 UTC, JFCotter commented on src/styles.css
> +  background-repeat: no-repeat;
done

2023-11-28 10:08 UTC, JFCotter commented on src/styles.css
> +#year {
changed to class

2023-11-28 10:08 UTC, JFCotter commented on src/styles.css
> +span {
done

2023-11-28 10:08 UTC, JFCotter commented on src/styles.css
> +  margin-bottom: 40px;
done

2023-11-28 10:08 UTC, JFCotter commented on src/styles.css
> +main {
done

2023-11-28 10:08 UTC, JFCotter commented on src/styles.css
> +h1 {
done

2023-11-28 10:08 UTC, JFCotter commented on src/styles.css
> +  color: white;
done

2023-11-28 12:34 UTC, mkyorov-ageas requested changes

2023-11-28 12:34 UTC, ghost commented on src/styles.css
> +  margin: 1% 1% 1% 0;
never do margin in %

2023-11-28 12:34 UTC, ghost commented on src/styles.css
> +#password {
Don't use id for styling

2023-11-28 12:34 UTC, ghost commented on src/styles.css
> +  margin: auto;
You would usually have margin: 10px auto, where "auto" is for left and right to get positioned centre

2023-11-28 12:34 UTC, mkyorov-ageas commented on src/styles.css
> +  margin-bottom: 3%;
Never use % for spacings (margin & padding)

2023-11-28 12:34 UTC, mkyorov-ageas commented on src/styles.css
> +  border-style: hidden;
re-think the logic here.

2023-11-28 12:34 UTC, mkyorov-ageas commented on src/styles.css
> +  min-width: 30%;
Avoid using % when setting min/max values, as this is relative value

2023-11-28 12:34 UTC, mkyorov-ageas commented on src/styles.css
> +  margin-top: auto;
Re-think this please

2023-11-28 12:34 UTC, mkyorov-ageas commented on src/styles.css
> +  max-height: 40px;
Read about responsive images

2023-11-28 12:34 UTC, mkyorov-ageas commented on src/styles.css
> +    max-width: 96%;
Read about setting responsive layout

2023-11-29 10:17 UTC, merged